### 求1xn矩阵的翻转结果

In [ ]:
import numpy as np
data = np.array([1,2,3,4,5,6,7])

data_reverse = np.flip(data)

print(data_reverse)



[7 6 5 4 3 2 1]


### 生成一个10x10的随机数矩阵，并求每一列的最大值

In [30]:
matrix = np.random.random((10,10))

print(matrix.max(axis=0))


[0.96922717 0.93158009 0.93201531 0.87413963 0.88956037 0.69411462
 0.93922094 0.95469067 0.89341798 0.9169948 ]


### 对10x10随机数矩阵进行四舍五入

In [33]:
for i in range(0,10):
    for j in range(0,10):
        matrix[i,j] = matrix[i,j].round()
print(matrix)

[[0. 0. 0. 0. 1. 1. 0. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 1. 1. 0. 0. 1. 0. 1.]
 [0. 0. 1. 1. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 1. 1. 0. 1. 0. 0. 1.]
 [0. 0. 1. 1. 0. 0. 1. 0. 1. 1.]
 [0. 1. 0. 1. 1. 0. 0. 1. 0. 0.]
 [1. 1. 0. 0. 0. 0. 1. 1. 1. 0.]
 [1. 1. 1. 0. 1. 0. 1. 0. 1. 1.]]


### 求10x10随机矩阵每一列的平均值和标准差

In [34]:
print(matrix.mean(axis=0))
print(matrix.std(axis=0))

[0.3 0.3 0.5 0.6 0.6 0.1 0.4 0.4 0.4 0.6]
[0.45825757 0.45825757 0.5        0.48989795 0.48989795 0.3
 0.48989795 0.48989795 0.48989795 0.48989795]


### 对一个3x5x5的张量，第一维的每个矩阵和一个5x5的矩阵相乘

In [ ]:
tensor = np.random.randint(1,10,size = (3,5,5))
matrix = np.random.randint(1,10,size = (5,5))

m_result = np.zeros((3,5,5))
for i in range(3):
    m_result[i] = np.matmul(tensor[i],matrix)
print(m_result)

# 其实可以直接 result = tensor * matrix 
# numpy会自动广播

[[[100. 233. 112. 176. 209.]
  [ 80. 201. 112. 165. 188.]
  [ 61. 183.  90. 108. 152.]
  [ 53. 125.  64. 104. 118.]
  [101. 230. 106. 194. 211.]]

 [[ 95. 199. 102. 194. 205.]
  [ 57. 125.  70. 124. 130.]
  [ 99. 262. 140. 192. 232.]
  [ 69. 174.  84. 122. 151.]
  [ 39. 125.  92. 111. 138.]]

 [[ 38. 110.  78. 100. 124.]
  [106. 233. 108. 204. 213.]
  [ 80. 166.  76. 153. 157.]
  [ 63. 166.  96. 138. 170.]
  [111. 254. 110. 191. 217.]]]
